---
title: "About This Website"
---

This website was built using R and Rmarkdown.

Github: https://github.com/everhartlab/IntroR


Authors
-------

### Sydney E. Everhart

### Zhian N. Kamvar

 - Website: https://zkamvar.github.io
 - twitter: [@zkamvar](https://twitter.com/zkamvar)

I am a computational biologist currently working a post-doctoral researcher in the lab of [Dr. Sydney E. Everhart][see] at the [Department of Plant Pathology at University of Nebraska-Lincoln][unl]. My research focus seeks to understand the mechanisms that drive the evolution of clonal plant pathogens. 

I grew up in Cupertino, CA, but got my undergraduate degree in Biology at [Truman State University][tsu] in Kirksville, MO where I had a research opportunity to work on understanding the [regulation of shoot apical meristem development in maize][1]. After graduation, I spent three years teaching and making music in South Korea before going back to the US to pursue my graduate education.

My Ph. D. is from the [Department of Botany and Plant Pathology][bpp] at [Oregon State University][osu] where I worked in the lab of [Dr. Nik Grünwald][nik]. [My dissertation][diss] focuses on my development of computational tools for analyzing clonal populations in the R package [*poppr*][poppr].




[1]: https://doi.org/10.1534/genetics.106.066472
[bpp]: http://bpp.oregonstate.edu/
[osu]: http://oregonstate.edu/
[poppr]: https://github.com/grunwaldlab/poppr#readme
[diss]: https://zkamvar.github.io/dissertation
[see]: http://plantpathology.unl.edu/sydney-everhart
[unl]: http://plantpathology.unl.edu/
[tsu]: http://www.truman.edu/
[nik]: http://grunwaldlab.cgrb.oregonstate.edu
